version: "3.9"

services:
  samsubot_redis:
    image: redis:7
    container_name: samsubot_redis

  samsubot_postgres:
    image: postgres:14
    container_name: samsubot_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  samsubot_mongodb:
    image: mongo:6.0
    container_name: samsubot_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db

  samsubot_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: samsubot_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - samsubot_postgres
      - samsubot_mongodb
      - samsubot_redis

  samsubot_frontend:
    build:
      context: ./frontend/apps/samsubot-web
      dockerfile: Dockerfile
    container_name: samsubot_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - samsubot_backend

volumes:
  pgdata:
  mongodb_data: