version: "3.9"

services:
  samsubot_redis:
    image: redis:7
    container_name: samsubot_redis
    ports:
      - "6379:6379"

  samsubot_postgres:
    image: postgres:14
    container_name: samsubot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  samsubot_mongodb:
    image: mongo:6.0
    container_name: samsubot_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: samsubot
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  samsubot_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: samsubot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    env_file:
      - .env.dev
    depends_on:
      - samsubot_postgres
      - samsubot_mongodb
      - samsubot_redis
    environment:
      - MONGO_URI=mongodb://samsu:secret123@samsubot_mongodb:27017/samsubot

  samsubot_frontend:
    build:
      context: ./frontend/apps/samsubot-web
      dockerfile: Dockerfile
    container_name: samsubot_frontend
    ports:
      - "8080:80"
    depends_on:
      - samsubot_backend

volumes:
  pgdata:
  mongodb_data: