version: "3.9"

services:
  samsubot_redis:
    image: redis:7
    container_name: samsubot_redis
    ports:
      - "6379:6379"

  chroma:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma
    restart: unless-stopped

  samsubot_postgres:
    image: postgres:14
    container_name: samsubot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  samsubot_mongodb:
    image: mongo:6.0
    container_name: samsubot_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: samsubot
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  samsubot_llm:
    image: ollama/ollama
    container_name: samsubot_llm
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped

  samsubot_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: samsubot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    env_file:
      - .env.dev
    depends_on:
      - samsubot_postgres
      - samsubot_mongodb
      - samsubot_redis
      - samsubot_llm
    environment:
      - MONGO_URI=mongodb://samsu:secret123@samsubot_mongodb:27017/samsubot
      - SAMSUBOT_LLM_BASE_URL=http://samsubot_llm:11434

  samsubot_frontend:
    build:
      context: ./frontend/apps/samsubot-web
      dockerfile: Dockerfile
    container_name: samsubot_frontend
    ports:
      - "8080:80"
    depends_on:
      - samsubot_backend

volumes:
  pgdata:
  mongodb_data: