version: "3.9"

services:
  redis:
    image: redis:7
    container_name: samsubot_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14
    container_name: samsubot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0
    container_name: samsubot_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: samsubot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - mongo

  frontend:
    build:
      context: ./frontend/apps/samsubot-web
      dockerfile: Dockerfile
    container_name: samsubot_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
  mongodb_data:
